<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-OEQE97C" failures="1" tests="1" name="Register with valid data" time="11.623" errors="0" timestamp="2024-06-06T14:13:50 EET">
  <testcase classname="testcases.TC02_Registration_NewDesign" name="Regester_WithValidData_P" time="4.359">
    <failure type="java.lang.AssertionError" message="expected [https://demo.nopcommerce.com/register?returnurl=%2F] but found [https://demo.nopcommerce.com/registerresult/1?returnUrl=/]">
      <![CDATA[java.lang.AssertionError: expected [https://demo.nopcommerce.com/register?returnurl=%2F] but found [https://demo.nopcommerce.com/registerresult/1?returnUrl=/]
at testcases.TC02_Registration_NewDesign.Regester_WithValidData_P(TC02_Registration_NewDesign.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Regester_WithValidData_P -->
</testsuite> <!-- Register with valid data -->
